name: Build React App

on:
  push:
    branches:
      - main # Adjust this branch name as needed
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change the version if needed

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      # Add additional steps here, if needed.


