name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         node-version: 18.0.0
      
      - name: Update Npx
        run:  npx update-browserslist-db@latest
        
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build



